#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2015      Mark Wong
#               2015      2ndQuadrant, Ltd.

if [ $# -ne 1 ]; then
	echo "usage: `basename $0` <output_dir>"
	exit 1
fi

OUTPUT_DIR=$1

DBOUTPUT_DIR=$OUTPUT_DIR/db
mkdir -p $DBOUTPUT_DIR

VVERSION=`virtuoso-t --help 2>&1 | head -n 2 | tail -n 1`
echo "$VVERSION" > $DBOUTPUT_DIR/readme.txt

cp $VADDIR/virtuoso.ini $DBOUTPUT_DIR/param.txt
