#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2015      Mark Wong
#               2015      2ndQuadrant, Ltd.

isql PROMPT=OFF ERRORS=STDOUT VERBOSE=OFF << __
CREATE TABLE supplier (
    s_suppkey     INTEGER NOT NULL,
    s_name        CHAR(25) NOT NULL,
    s_address     VARCHAR(40) NOT NULL,
    s_nationkey   INTEGER NOT NULL,
    s_phone       CHAR(15) NOT NULL,
    s_acctbal     DOUBLE PRECISION NOT NULL,
    s_comment     VARCHAR(101) NOT NULL,
    PRIMARY KEY   (s_suppkey)
)
ALTER INDEX supplier ON supplier PARTITION (s_suppkey INT (0hexffff00));

CREATE TABLE part (
    p_partkey     INTEGER NOT NULL,
    p_name        VARCHAR(55) NOT NULL,
    p_mfgr        CHAR(25) NOT NULL,
    p_brand       CHAR(10) NOT NULL,
    p_type        VARCHAR(25) NOT NULL,
    p_size        INTEGER NOT NULL,
    p_container   CHAR(10) NOT NULL,
    p_retailprice DOUBLE PRECISION NOT NULL,
    p_comment     VARCHAR(23) NOT NULL,
    PRIMARY KEY   (p_partkey)
)
ALTER INDEX part ON part PARTITION (p_partkey INT (0hexffff00));

CREATE TABLE partsupp (
    ps_partkey     INTEGER NOT NULL,
    ps_suppkey     INTEGER NOT NULL,
    ps_availqty    INTEGER NOT NULL,
    ps_supplycost  DOUBLE PRECISION NOT NULL,
    ps_comment     VARCHAR (199) NOT NULL,
    PRIMARY KEY    (ps_partkey, ps_suppkey)
)
ALTER INDEX partsupp ON partsupp PARTITION (ps_partkey INT (0hexffff00));

CREATE TABLE customer (
    c_custkey     INTEGER NOT NULL,
    c_name        VARCHAR(25) NOT NULL,
    c_address     VARCHAR(40) NOT NULL,
    c_nationkey   INTEGER NOT NULL,
    c_phone       CHAR(15) NOT NULL,
    c_acctbal     DOUBLE PRECISION   NOT NULL,
    c_mktsegment  CHAR(10) NOT NULL,
    c_comment     VARCHAR(117) NOT NULL,
    PRIMARY KEY   (c_custkey)
)
ALTER INDEX customer ON customer PARTITION (c_custkey INT (0hexffff00));

CREATE TABLE orders (
    o_orderkey       INTEGER NOT NULL,
    o_custkey        INTEGER NOT NULL,
    o_orderstatus    CHAR(1) NOT NULL,
    o_totalprice     double precision NOT NULL,
    o_orderdate      DATE NOT NULL,
    o_orderpriority  CHAR(15) NOT NULL,
    o_clerk          CHAR(15) NOT NULL,
    o_shippriority   INTEGER NOT NULL,
    o_comment        VARCHAR(79) NOT NULL,
    PRIMARY KEY      (o_orderkey)
)
ALTER INDEX orders ON orders PARTITION (o_orderkey INT (0hexffff00));

CREATE TABLE lineitem (
    l_orderkey    INTEGER NOT NULL,
    l_partkey     INTEGER NOT NULL,
    l_suppkey     INTEGER NOT NULL,
    l_linenumber  INTEGER NOT NULL,
    l_quantity    DOUBLE PRECISION NOT NULL,
    l_extendedprice  DOUBLE PRECISION NOT NULL,
    l_discount    DOUBLE PRECISION NOT NULL,
    l_tax         DOUBLE PRECISION NOT NULL,
    l_returnflag  CHAR(1) NOT NULL,
    l_linestatus  CHAR(1) NOT NULL,
    l_shipdate    DATE NOT NULL,
    l_commitdate  DATE NOT NULL,
    l_receiptdate DATE NOT NULL,
    l_shipinstruct CHAR(25) NOT NULL,
    l_shipmode     CHAR(10) NOT NULL,
    l_comment      VARCHAR(44) NOT NULL,
    PRIMARY KEY    (l_orderkey, l_linenumber)
)
ALTER INDEX lineitem ON lineitem PARTITION (l_orderkey INT (0hexffff00));

CREATE INDEX o_ck ON ORDERS (o_custkey) PARTITION (o_custkey INT (0hexffff00));

CREATE TABLE nation (
    n_nationkey  INTEGER NOT NULL,
    n_name 	 CHAR(25) NOT NULL,
    n_regionkey  INTEGER NOT NULL,
    n_comment    VARCHAR(152),
    PRIMARY KEY  (n_nationkey)
)
ALTER INDEX nation ON nation PARTITION CLUSTER REPLICATED;

CREATE TABLE region (
    r_regionkey  INTEGER NOT NULL,
    r_name       CHAR(25) NOT NULL,
    r_comment    VARCHAR(152),
    PRIMARY KEY  (r_regionkey)
)
ALTER INDEX region ON region PARTITION CLUSTER REPLICATED;

CREATE TABLE time_statistics (
	task_name VARCHAR(40),
	s_time DATETIME,
	e_time DATETIME
);

sequence_set('dataset', 1, 0);
__

exit $?
