#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2006 Jenny Zhang
#               2002-2006 Open Source Development Labs, Inc.
#               2014      Mark Wong
#               2014      2ndQuadrant, Ltd.
#

GENERATE=0
PARAMETERS=""
ONLY_LOAD=0
SF=0
USE_LINUXPERF=0
USE_OPROFILE=0

while getopts "f:g:lo:p:tyY" opt; do
	case $opt in
	f)
		SF=$OPTARG
		;;
	g)
		GENERATE=$OPTARG
		;;
	l)
		ONLY_LOAD=1
		;;
	o)
		OUTPUT_DIR=$OPTARG
		mkdir -p $OUTPUT_DIR
		;;
	p)
		PARAMETERS="-p \"${LOAD_PARAMETERS} $OPTARG\""
		;;
	t)
		TABLESPACE_FLAG="-t -b"
		;;
	y)
		USE_OPROFILE=1
		;;
	Y)
		USE_LINUXPERF=1
		;;
	?)
		echo "Usage: $0 [-o <dir> -p <db_param> -f <scale_factor>]"
		exit 1
	esac
done

# Check to see if we have the files. If we don't have them - create them. 
have_all_files=0
for f in customer lineitem  nation  orders  partsupp  part  region  supplier ; do
    if ! test -f $DSS_PATH/$f.tbl ; then
        have_all_files=1
    fi
done

if [ $GENERATE -ne 0 -o $have_all_files -eq 1 ]; then
	echo "Generating data for scale factor $SF..."
	# DBGEN reads DSS_PATH env var to determine where to put the files
	${DBGEN} -s $SF || exit 1
	chmod a+r ${DSS_PATH}/*.tbl
else
	echo "Create the database using existing datafiles."
fi

# Initialize profile counters.
if [ -f /proc/profile ]; then
	clearprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	clearoprof
fi

dbt3-mysql-create-db -o ${OUTPUT_DIR} ${PARAMETERS} || exit 1
	
dbt3-mysql-drop-tables
dbt3-mysql-create-tables || exit 1

# Start collecting system statistics.
dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 || exit 1

# Collect database statistics
dbt3-mysql-dbstat ${OUTPUT_DIR} 2> /dev/null &

echo "`date +'%Y-%m-%d %H:%M:%S'` Starting Load Test..."
s_time=`date +%s`
dbt3-mysql-time-statistics -s -n "LOAD" || exit 1

if [ $USE_LINUXPERF -eq 1 ]; then
	PERFDIR=$OUTPUT_DIR/perf
	mkdir -p $PERFDIR
	PERFCOMMAND="perf record -a -g -s -F 100 -o $PERFDIR/perf.data"
fi

eval $PERFCOMMAND dbt3-mysql-load-data || exit 1

dbt3-mysql-time-statistics -e -n "LOAD" || exit 1
e_time=`date +%s`
echo "`date +'%Y-%m-%d %H:%M:%S'` Load Test Completed"
diff_time=`expr $e_time - $s_time`
echo "Elapsed time for Load Test : $diff_time seconds"

# Stop collecting system statistics.
read SARPID < $OUTPUT_DIR/sar.pid
kill $SARPID
read PIDSTATPID < $OUTPUT_DIR/pidstat.pid
kill $PIDSTATPID
#read DBSTATPID < $OUTPUT_DIR/dbstat.pid
#kill $DBSTATPID

# Collect profile data.
if [ -f /proc/profile ]; then
	profname='Load_Test'
	getprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	profname='Load_Test'
	getoprof
fi

if [ $USE_LINUXPERF -eq 1 ]; then
	echo "Generating Linux perf reports for load test..."
	perf report -i $PERFDIR/perf.data -n > $PERFDIR/perf-report.txt \
			2>> $OUTPUT_DIR/perf/report-output.txt &
	perf annotate -l -P -i $PERFDIR/perf.data > $PERFDIR/perf-annotate.txt \
			2>> $OUTPUT_DIR/perf/report-output.txt &
	perf script -L -i $PERFDIR/perf.data > $PERFDIR/perf-trace.txt \
			2>> $OUTPUT_DIR/perf/report-output.txt &
fi
