#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2006      Open Source Development Labs, Inc.
#               2006-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

if [ "x" = "x${MYDATA}" ]; then
	echo "ERROR: MYDATA must be set"
	exit 1
fi

HOSTNAME=`hostname`
PIDFILE=$MYDATA/$HOSTNAME.pid

if [ ! -f "$PIDFILE" ]; then
	echo "MySQL pid file '$PIDFILE' does not exist."
	echo "MySQL was not stopped, if it was running."
	exit 0
fi
read MYSQL_PID < $PIDFILE
kill ${MYSQL_PID} || exit 1
sleep 10
echo "MySQL stopped successfully (by kill)."

exit 0
