#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labss, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

engine=`echo $MYSQL_ENGINE | tr 'A-Z' 'a-z' `
MYSQL="mysql -u root -D $DBNAME -s"

# Create tables
create_table() {
    table=${1}
    if [ -f $DSS_QUERY/ddl/$engine/${table}.sql ] ; then 
	cat $DSS_QUERY/ddl/$engine/${table}.sql | $MYSQL || exit 1
    else
        cat $DSS_QUERY/ddl/${table}.sql | $MYSQL || exit 1
    fi
}

while getopts "bd:e:" OPT; do
    case ${OPT} in
	b)
	BACKGROUND=yes
	;;
	d)
	DBDATA=${OPTARG}
	;;
	e)
	MYSQL_ENGINE=${OPTARG}
	;;
    esac
done


create_table supplier 
create_table part
create_table partsupp
create_table customer
create_table orders
create_table lineitem
create_table nation
create_table region

$MYSQL << __EOF__
CREATE TABLE time_statistics (
	task_name VARCHAR(40),
	s_time TIMESTAMP default current_timestamp,
	e_time TIMESTAMP,
	int_time INTEGER);
CREATE TABLE dataset (
	id INTEGER NOT NULL,
	count INTEGER NOT NULL,
	PRIMARY KEY (count));
INSERT INTO dataset (id, count)
VALUES (1, 0);
__EOF__
