#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

MYSQL="mysql -u root -D $DBNAME -s"

$MYSQL -e "ALTER TABLE supplier ADD PRIMARY KEY (s_suppkey);" &
$MYSQL -e "ALTER TABLE region ADD PRIMARY KEY (r_regionkey);" &
$MYSQL -e "ALTER TABLE partsupp ADD PRIMARY KEY (ps_partkey, ps_suppkey);" &
$MYSQL -e "ALTER TABLE part ADD PRIMARY KEY (p_partkey);" &
$MYSQL -e "ALTER TABLE orders ADD PRIMARY KEY (o_orderkey);" &
$MYSQL -e "ALTER TABLE nation ADD PRIMARY KEY (n_nationkey);" &
$MYSQL -e "ALTER TABLE lineitem ADD PRIMARY KEY (l_orderkey, l_linenumber);" &
$MYSQL -e "ALTER TABLE customer ADD PRIMARY KEY (c_custkey);" &

$MYSQL -e "CREATE INDEX i_s_nationkey ON supplier (s_nationkey);" &
$MYSQL -e "CREATE INDEX i_ps_partkey ON partsupp (ps_partkey);" &
$MYSQL -e "CREATE INDEX i_ps_suppkey ON partsupp (ps_suppkey);" &
$MYSQL -e "CREATE INDEX i_o_orderdate ON orders (o_orderdate);" &
$MYSQL -e "CREATE INDEX i_o_custkey ON orders (o_custkey);" &
$MYSQL -e "CREATE INDEX i_n_regionkey ON nation (n_regionkey);" &
$MYSQL -e "CREATE INDEX i_l_shipdate ON lineitem (l_shipdate);" &
$MYSQL -e "CREATE INDEX i_l_suppkey_partkey ON lineitem (l_partkey, l_suppkey);" &
$MYSQL -e "CREATE INDEX i_l_partkey ON lineitem (l_partkey);" &
$MYSQL -e "CREATE INDEX i_l_suppkey ON lineitem (l_suppkey);" &
$MYSQL -e "CREATE INDEX i_l_receiptdate ON lineitem (l_receiptdate);" &
$MYSQL -e "CREATE INDEX i_l_orderkey ON lineitem (l_orderkey);" &
$MYSQL -e "CREATE INDEX i_l_orderkey_quantity ON lineitem (l_orderkey, l_quantity);" &
$MYSQL -e "CREATE INDEX i_l_commitdate ON lineitem (l_commitdate);" &
$MYSQL -e "CREATE INDEX i_c_nationkey ON customer (c_nationkey);" &

wait

$MYSQL -e "analyze table supplier"
$MYSQL -e "analyze table part"
$MYSQL -e "analyze table partsupp"
$MYSQL -e "analyze table customer"
$MYSQL -e "analyze table orders"
$MYSQL -e "analyze table lineitem"
$MYSQL -e "analyze table nation"
$MYSQL -e "analyze table region"
