#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labss, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

MYSQL="mysql -u root -D $DBNAME -s"

# Load tables
# This background stuff is honestly kinda ugly. IMO the right way to do this is
# to utilize make -j
load_table() {
    table=${1}
    if [ x${2} == x ]; then
	file=${table}.tbl
    else
	file=${2}.tbl
    fi
    # This disable/enable trick only works on MyISAM for the moment. 
    $MYSQL -e "alter table $table disable keys;"
    mysqlimport -u root --fields-terminated-by='|' ${DBNAME} ${DBDATA}/${file}
    $MYSQL -e "alter table $table enable keys;"
}

while getopts "bd:e:" OPT; do
    case ${OPT} in
	b)
	BACKGROUND=yes
	;;
	d)
	DBDATA=${OPTARG}
	;;
    esac
done

load_table supplier &
load_table part &
load_table partsupp &
load_table customer &
load_table orders &
load_table lineitem &
load_table nation &
load_table region &

wait
