#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Jenny Zhang
#               2003-2006 Open Source Development Labs, Inc.
#               2014      Mark Wong
#               2014      2ndQuadrant, Ltd.
#

if [ $# -ne 5 ]; then
        echo "Usage: $0 <scale_factor> <stream_num> <0/1 - explain analyze off/on> <run dir> <seed file>"
        exit 1
fi

scale_factor=$1
stream_num=$2
EXPLAIN_ANALYZE=$3
OUTPUT_DIR=$4
SEED_FILE=$5

MYSQL="mysql -u root -D $DBNAME -s"
RUNDIR=$OUTPUT_DIR/run
RESULTSDIR="$OUTPUT_DIR/results/$stream_num"

# output PID to a tmp file
echo "$$" > $RUNDIR/PID$stream_num

if [ ! -f $SEED_FILE ]; then
	echo "creating seed file $SEED_FILE, you can change the seed by "
	echo "modifying this file"
	$SRCDIR/scripts/init_seed.sh > $SEED_FILE
fi

seed=`cat $SEED_FILE`

seed=$(( $seed + $stream_num ))

# get the execution plan for each query
PLANDIR=$OUTPUT_DIR/db/plans/$stream_num
mkdir -p $PLANDIR
i=1
while [ $i -le 22 ]
do
	Q=`$QGEN -c -r $SEED -p 0 -s $scale_factor $i`
	N=`echo $Q | sed -n -r 's/.*\(#\)([[:digit:]]+)\..*/\1/p'`
	mysql -u root -D $DBNAME << __EOF__ > $PLANDIR/$N.txt
$Q
__EOF__
	i=$(( $i + 1 ))
done

# run the queries
echo "`date`: start throughput queries for stream $stream_num "
s_time=`date +%s`
STREAMTASK="PERF.THRUPUT.QS$stream_num.ALL"
dbt3-mysql-time-statistics -s -n $STREAMTASK || exit 1
i=1
while [ $i -le 22 ]; do
	Q=`$QGEN -c -r $SEED -p $stream_num -s $scale_factor $i`
	N=`echo $Q | sed -n -r 's/.*\(#\)([[:digit:]]+)\..*/\1/p'`
	TASK="PERF.THRUPUT.QS$stream_num.Q$N"
	dbt3-mysql-time-statistics -s "$TASK" || exit 1
	$MYSQL << __EOF__ > $RESULTSDIR/$N.txt
$Q
__EOF__
	dbt3-mysql-time-statistics -e "$TASK" || exit 1
	i=$(( $i + 1 ))
done
dbt3-mysql-time-statistics -e -n $STREAMTASK || exit 1
e_time=`date +%s`
echo "`date`: end queries "
diff_time=$(( $e_time - $s_time ))
echo "elapsed time for queries $diff_time"
