#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Jenny Zhang
#               2003-2006 Open Source Development Labs, Inc.
#               2004-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

USE_OPROFILE=0

TEST_ARGS=
NO_REFRESH_FLAG=

while getopts "ef:n:o:p:s:yz" opt; do
	case $opt in
	e) TEST_ARGS="$TEST_ARGS -e"
		;;
	f) scale_factor=$OPTARG
		;;
	n) num_stream=$OPTARG
		;;
	o) OUTPUT_DIR=$OPTARG
	   mkdir -p $OUTPUT_DIR/results
		;;
	p) PARAMETERS="${THROUGHPUT_PARAMETERS} $OPTARG"
		;;
	s) SEED_FILE=$OPTARG
		;;
	y) USE_OPROFILE=1
		;;
	z) NO_REFRESH_FLAG="-z"
		;;
	esac
done

read SEED < $SEED_FILE
echo "Seed : $SEED" > $OUTPUT_DIR/readme.txt

RUNDIR=$OUTPUT_DIR/run
mkdir -p $RUNDIR

# Clear the read profile counters.
if [ -f /proc/profile ]; then
	clearprof
fi

# Clear the oprofile counters.
if [ $USE_OPROFILE -eq 1 ]; then
	clearoprof
fi

dbt3-mysql-stop-db
dbt3-mysql-start-db -o $OUTPUT_DIR

s_time=`date +%s`
dbt3-mysql-time-statistics -s -n "PERF.THRUPUT" || exit 1

# Start collecting system statistics. 
dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 || exit 1

# Start collecting database statistics.
dbt3-mysql-dbstat $OUTPUT_DIR 2> /dev/null &

# Start the streams.

dbt3-mysql-throughput-stream-wrapper -f $scale_factor -n $num_stream \
		$TEST_ARGS -o $OUTPUT_DIR -s $SEED_FILE $NO_REFRESH_FLAG
if [ $? -eq 1 ] ; then
  echo "dbt3-throughput-stream-wrapper problem"
  exit 1
fi

# Stop collecting system statistics.
echo "Stopping system statistics"
read SARPID < $OUTPUT_DIR/sar.pid
kill $SARPID
read PIDSTATPID < $OUTPUT_DIR/pidstat.pid
kill $PIDSTATPID
#read DBSTATPID < $OUTPUT_DIR/dbstat.pid
#kill $DBSTATPID

dbt3-mysql-time-statistics -e -n "PERF.THRUPUT" || exit 1
e_time=`date +%s`
diff_time=$(( $e_time - $s_time ))
echo "Stream: Elapsed time for Throughput Test : $diff_time seconds"

# Stop the database after the test.
dbt3-mysql-stop-db

if [ -f /proc/profile ]; then
	profname="Throughput_Test"
	getprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	profname="Throughput_Test"
	getoprof
fi
