#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Open Source Development Labs, Inc.
#               2003-2006 Jenny Zhang
#               2005-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

record_start()
{
	NAME=$1

	psql -v ON_ERROR_STOP=1 -X -q << __EOF__ > /dev/null 2>&1
INSERT INTO time_statistics (task_name, s_time)
VALUES ('${NAME}', CURRENT_TIMESTAMP);
__EOF__
}

record_end()
{
	NAME=$1

	psql -v ON_ERROR_STOP=1 -X -q << __EOF__ > /dev/null 2>&1
UPDATE time_statistics
SET e_time = current_timestamp
WHERE task_name = '${NAME}';
__EOF__
}

EXPLAIN=0
USE_LINUXPERF=0

while getopts "f:n:o:s:t:yY" opt; do
	case $opt in
	f) SCALE_FACTOR=$OPTARG;;
	n) num_stream=$OPTARG;;
	o) OUTPUT_DIR=$OPTARG
		mkdir -p $OUTPUT_DIR/results
		;;
	s) SEED_FILE=$OPTARG;;
	t) stream_num=$OPTARG;;
	y) EXPLAIN=1
		EXPLAIN_ARG="-y"
		;;
	Y) USE_LINUXPERF=1;;
	\?) exit 1;;
	esac
done
PSQL="psql -v ON_ERROR_STOP=1 -X -e"
RUNDIR=$OUTPUT_DIR/run
RESULTSDIR="${OUTPUT_DIR}/results/${stream_num}"
mkdir -p ${RESULTSDIR} || exit 1

# output PID to a tmp file
echo "$$" > $RUNDIR/PID$stream_num

if [ ! -f $SEED_FILE ]; then
	echo "creating seed file $SEED_FILE, you can change the seed by "
	echo "modifying this file"
	$SRCDIR/scripts/init_seed.sh > $SEED_FILE
fi
read SEED < $SEED_FILE
SEED=$(( ${SEED} + ${stream_num} ))

# get the execution plan for each query of each query stream
PLANDIR=${OUTPUT_DIR}/plans/${stream_num}
mkdir -p ${PLANDIR} || exit 1

i=1
while [ $i -le 22 ]
do
	# Remember the query planned is in the order determined by the seed.
	Q=`${QGEN} -c -r ${SEED} -p ${stream_num} -s ${SCALE_FACTOR} -x ${i}`
	N=`echo ${Q} | sed -n -r 's/.*\(#\)([[:digit:]]+)\..*/\1/p'`
	${PSQL} << __EOF__ > ${PLANDIR}/${N}.txt
${Q}
__EOF__
	i=$(( $i + 1 ))
done

# run the queries
echo "`date`: start throughput queriy stream $stream_num "
s_time=`date +%s`
STREAMTASK="PERF.THRUPUT.QS${stream_num}.ALL"
record_start "${STREAMTASK}" || exit 1
i=1
while [ ${i} -le 22 ]; do
	Q=`$QGEN -c -r $SEED -p $stream_num -s $SCALE_FACTOR $EXPLAIN_ARG $i`
	N=`echo ${Q} | sed -n -r 's/.*\(#\)([[:digit:]]+)\..*/\1/p'`
	if [ $USE_LINUXPERF -eq 1 ]; then
		PERFDIR=$RESULTSDIR/perf/$N
		mkdir -p $PERFDIR
		PERFCOMMAND="perf record -a -g -s -F 100 -o $PERFDIR/q$N-perf.data"
	fi
	TASK="PERF.THRUPUT.QS${stream_num}.Q${N}"
	record_start "${TASK}" || exit 1
	eval $PERFCOMMAND $PSQL << __EOF__ > $RESULTSDIR/$N.txt
$Q
__EOF__
	record_end "${TASK}" || exit 1
	i=$(( ${i} + 1 ))
done
record_end "${STREAMTASK}" || exit 1
e_time=`date +%s`
echo "`date`: end throughput query stream ${stream_num}"
diff_time=$(( $e_time - $s_time ))
echo "elapsed time for throughput query stream ${stream_num}: $diff_time sec"

if [ $EXPLAIN -eq 1 ]; then
	# Generate plan disaster report only if EXPLAIN ANALYZE is used.
	DISASTERCSV=$RESULTSDIR/disaster.csv
	i=1
	while [ $i -le 22 ]; do
		dbt3-pgsql-plan-disaster $RESULTSDIR/$i.txt >> $DISASTERCSV
		i=$(( $i + 1 ))
	done
	sort -n -t "," -k 2 -r -o $DISASTERCSV $DISASTERCSV
fi
