#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003      Open Source Development Lab, Inc.
#               2005-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

if [ $# -ne 2 ]; then
        echo "Usage: $0 <db port> <stream>"
        exit 1
fi

DBPORT=$1
set_num=$2

PSQL="psql -X -p ${DBPORT} -d ${SID}"

echo "`date`: Stream ${set_num} : Starting Refresh Stream 1..."
s_time=`date +%s`

${PSQL} -c "COPY lineitem FROM '${DSS_PATH}/lineitem.tbl.u$set_num' USING DELIMITERS '|';" &
${PSQL} -c "COPY orders FROM '${DSS_PATH}/orders.tbl.u$set_num' USING DELIMITERS '|';" &
wait

e_time=`date +%s`
echo "`date`: Stream ${set_num} : Refresh Stream 1 completed."
diff_time=$(( $e_time - $s_time ))
echo "Stream ${set_num} : Elapsed time for Refresh Stream 1 : $diff_time seconds"
