#!/bin/sh
#
# This file is released under the terms of the Artistic License.  Please see
# the file LICENSE, included in this package, for details.
#
# Copyright (C) 2006      Open Source Development Labs, Inc.
#               2006-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

cmd_clear=0
cmd_start=0
cmd_end=0

while getopts "cen:s" opt; do
	case $opt in
	c)
		cmd_clear=1
		;;
	e)
		cmd_end=1
		;;
	n)
		NAME=$OPTARG
		;;
	s)
		cmd_start=1
		;;
	\?)
		exit 1
		;;
	esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X -q"

if [ $cmd_clear -eq 1 ]; then
    SQL="DELETE FROM time_statistics"
fi;

if [ $cmd_start -eq 1 ]; then
    SQL="INSERT INTO time_statistics (task_name, s_time) 
         VALUES ('$NAME', CURRENT_TIMESTAMP)"
fi;

if [ $cmd_end -eq 1 ]; then
    SQL="UPDATE time_statistics SET e_time = CURRENT_TIMESTAMP WHERE task_name = '$NAME'"
fi;

$PSQL -c "$SQL"
exit $?
