#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2006 Open Source Development Labs, Inc.
#               2002-2006 Jenny Zhang
#               2005-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

# 15 July 2004 - Revamped by Mark Wong

DIR=`dirname $0`
. ${DIR}/../dbt3_profile || exit 1

SRCDIR=${DBT3_HOME}

DBSCRIPTDIR=$SRCDIR/scripts/pgsql

DBSTATS="$DBSCRIPTDIR/db_stats.sh"

PARAMETERS=""
SF=0
USE_OPROFILE=0
USE_LINUXPERF=0
GENERATE=0
ONLY_LOAD=0
DBDATA=${DSS_PATH}
WORKLOAD="H"
while getopts "d:f:g:lo:p:RtyYz:" opt; do
	case $opt in
	d)
		DBDATA=${OPTARG}
		export DSS_PATH=$DBDATA
		mkdir -p $DSS_PATH
		;;
	f)
		SF=$OPTARG
		;;
	g)
		GENERATE=$OPTARG
		;;
	l)
		ONLY_LOAD=1
		;;
	o)
		OUTPUT_DIR=$OPTARG
		mkdir -p $OUTPUT_DIR
		;;
	p)
		PARAMETERS="${LOAD_PARAMETERS} $OPTARG"
		PARAMETERS_ARG="-p \"${LOAD_PARAMETERS} $OPTARG\""
		;;
	R)
		WORKLOAD="R"
		WORKLOAD_ARG="-R"
		;;
	t)
		TABLESPACE_FLAG="-t -b"
		;;
	y)
		USE_OPROFILE=1
		;;
	Y)
		USE_LINUXPERF=1
		;;
	z)
		DBPORT=$OPTARG
		;;
	?)
		echo "Usage: $0 [-o <dir> -p <db_param> -f <scale_factor>]"
		exit 1
	esac
done

if test -z $OUTPUT_DIR ; then 
  OUTPUT_DIR=$DBSCRIPTDIR/output
  mkdir -p $OUTPUT_DIR
fi

# Check to see if we have the files. If we don't have them - create them. 
have_all_files=0
for f in customer lineitem  nation  orders  partsupp  part  region  supplier ; do
    if ! test -f $DSS_PATH/$f.tbl ; then
        have_all_files=1
    fi
done

if [ $GENERATE -ne 0 -o $have_all_files -eq 1 ]; then
	echo "Generating data for scale factor $SF..."
	date
	# DBGEN reads DSS_PATH env var to determine where to put the files
	${DBGEN} -s $SF || exit 1
	chmod a+r ${DSS_PATH}/*.tbl
	date
else
	echo "Create the database using existing datafiles."
fi

# Start collecting system statistics.
$SRCDIR/scripts/dbt3-sysstats --outdir $OUTPUT_DIR --iter 1440 --sample 60 || exit 1

$DBSCRIPTDIR/dbt3-pgsql-create-db -o ${OUTPUT_DIR} -l ${DBPORT} \
		${PARAMETERS_ARG}
	
date
${DBSCRIPTDIR}/dbt3-pgsql-drop-tables -l ${DBPORT} || exit 1
${DBSCRIPTDIR}/dbt3-pgsql-create-tables -d ${DBDATA} -l ${DBPORT} ${TABLESPACE_FLAG} || exit 1
date

echo "`date` Load Test Starting..."
s_time=`date +%s`
record_start "LOAD" || exit 1

# Collect database statistics
${DBSTATS} ${OUTPUT_DIR} ${DBPORT} 2> /dev/null &

# Initialize profile counters.
if [ -f /proc/profile ]; then
	clearprof
fi

if [ ${USE_OPROFILE} -eq 1 ]; then
	clearoprof
fi

if [ ${USE_LINUXPERF} -eq 1 ]; then
	perf_start ${OUTPUT_DIR}/perf &
fi

${DBSCRIPTDIR}/dbt3-pgsql-load-data -d ${DBDATA} || exit 1

if [ ${ONLY_LOAD} -eq 0 ]; then
	echo -n "Building indexes... "
	date
	${DBSCRIPTDIR}/dbt3-pgsql-create-indexes -l ${DBPORT} ${TABLESPACE_FLAG} \
			${WORKLOAD_ARG} || exit 1
	echo -n "Done building indexes... "
	date
fi

record_end "LOAD" || exit 1
e_time=`date +%s`
echo "`date +'%Y-%m-%d %H:%M:%S'` Load Test Completed"
diff_time=`expr $e_time - $s_time`
echo "Elapsed time for Load Test : $diff_time seconds"

# Stop collecting system statistics.
read SARPID < ${OUTPUT_DIR}/sar.pid
kill ${SARPID}
read PIDSTATPID < ${OUTPUT_DIR}/pidstat.pid
kill ${PIDSTATPID}
read DBSTATSPID < ${OUTPUT_DIR}/db_stats.pid
kill ${DBSTATSPID}

# Collect profile data.
if [ -f /proc/profile ]; then
	profname='Load_Test'
	getprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	profname='Load_Test'
	getoprof
fi

if [ ${USE_LINUXPERF} -eq 1 ]; then
	perf_collect ${OUTPUT_DIR}/perf
fi

exit 0
