#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Open Source Development Labs, Inc.
#               2003-2006 Jenny Zhang
#               2004-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

EXPLAIN=0
EXPLAIN_ARG=
USE_OPROFILE=0
USE_LINUXPERF=0
NO_REFRESH=0

record_start()
{
	local NAME=$1

	psql -v ON_ERROR_STOP=1 -X -q << __EOF__ > /dev/null 2>&1
INSERT INTO time_statistics (task_name, s_time)
VALUES ('${NAME}', CURRENT_TIMESTAMP);
__EOF__
}

record_end()
{
	local NAME=$1

	psql -v ON_ERROR_STOP=1 -X -q << __EOF__ > /dev/null 2>&1
UPDATE time_statistics
SET e_time = current_timestamp
WHERE task_name = '${NAME}';
__EOF__
}

# process the command line parameters
while getopts "ef:p:o:s:yYz" opt; do
	case $opt in
		e)
			EXPLAIN=1
			EXPLAIN_ARG="-y"
			;;
		f)
			SCALE_FACTOR=$OPTARG
			;;
		o)
			OUTPUT_DIR=$OPTARG
			RESULTSDIR="${OUTPUT_DIR}/results"
			mkdir -p ${RESULTSDIR}
			;;
		p)
			PARAMETERS_ARG="-p \"$OPTARG\""
			;;
		s)
			SEED_FILE=$OPTARG
			;;
		y)
			USE_OPROFILE=1
			;;
		Y)
			USE_LINUXPERF=1
			;;
		z)
			NO_REFRESH=1
			;;
		\?)
			echo "Usage: $0 -f <SCALE_FACTOR> [-e -p <db_params> -t <tag> -y]"
			exit 1
			;;
		esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X -e"

# Generate queries for the Power test.
SEED=`cat $SEED_FILE`
echo "Seed : $SEED" > $OUTPUT_DIR/readme.txt

# Get the EXPLAIN plans for only the SELECT statements.
PLANDIR=${OUTPUT_DIR}/plans
mkdir -p ${PLANDIR} || exit 1
i=1
while [ ${i} -le 22 ]; do
	# Remember the query planned is in the order determined by the seed.
	Q=`${QGEN} -c -r ${SEED} -p 0 -s ${SCALE_FACTOR} -x ${i}`
	N=`echo ${Q} | sed -n -r 's/.*\(#\)([[:digit:]]+)\..*/\1/p'`
	${PSQL} << __EOF__ > ${PLANDIR}/${N}.txt
${Q}
__EOF__
	i=$(( ${i} + 1 ))
done

dbt3-pgsql-stop-db || exit 1
eval dbt3-pgsql-start-db -o $OUTPUT_DIR $PARAMETERS_ARG || exit 1

# Start collecting system statistics.
dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 || exit 1

# Collect database statistics
dbt3-pgsql-dbstat ${OUTPUT_DIR} &

# Clear the read profile counters.
if [ -f /proc/profile ]; then
	clearprof
fi

# Clear the oprofile counters.
if [ $USE_OPROFILE -eq 1 ]; then
	clearoprof
fi

s_time_power=`date +%s`
psql -v ON_ERROR_STOP=1 -X -q << __EOF__ > /dev/null 2>&1
INSERT INTO time_statistics (task_name, s_time)
VALUES ('PERF.POWER', CURRENT_TIMESTAMP);
__EOF__

if [ ${NO_REFRESH} -eq 0 ]; then
	# Refresh Stream 1
	echo "`date`: Power Test : Starting Refresh Stream 1" 
	s_time=`date +%s`
	TASK="PERF.POWER.RF1"
	record_start "${TASK}" || exit 1
	dbt3-pgsql-rf1 ${SCALE_FACTOR} > ${RESULTSDIR}/rf1.txt 2>&1
	DATASET=$?
	if [ ${DATASET} -lt 1 ]; then
		exit 1
	fi
	record_end "${TASK}" || exit 1
	e_time=`date +%s`
	echo "`date`: Power Test : Refresh Stream 1 completed." 
	diff_time=$(( $e_time - $s_time ))
fi

# Execute the queries.
i=1
while [ ${i} -le 22 ]; do
	if [ $USE_LINUXPERF -eq 1 ]; then
		PERFDIR=$OUTPUT_DIR/perf/$N
		mkdir -p $PERFDIR
		PERFCOMMAND="perf record -a -g -s -F 100 -o $PERFDIR/q$N-perf.data"
	fi
	Q=`${QGEN} -c -r ${SEED} -p 0 -s ${SCALE_FACTOR} ${EXPLAIN_ARG} ${i}`
	N=`echo ${Q} | sed -n -r 's/.*\(#\)([[:digit:]]+)\..*/\1/p'`
	TASK="PERF.POWER.Q${N}"
	record_start "${TASK}" || exit 1
	eval $PERFCOMMAND $PSQL << __EOF__ \
			> $RESULTSDIR/$N.txt 2>> $OUTPUT_DIR/power.txt
${Q}
__EOF__
	record_end "${TASK}" || exit 1
	i=$(( ${i} + 1 ))
done

if [ ${NO_REFRESH} -eq 0 ]; then
	# Refresh Stream 2
	echo "`date`: Power Test : Starting Refresh Stream 2" 
	s_time=`date +%s`
	TASK="PERF.POWER.RF2"
	record_start "${TASK}" || exit 1
	dbt3-pgsql-rf2 ${DATASET} > ${RESULTSDIR}/rf2.txt 2>&1 || exit 1
	record_end "${TASK}" || exit 1
	e_time=`date +%s`
	echo "`date`: Power Test : Refresh Stream 2 completed." 
	diff_time=$(( $e_time - $s_time ))
fi

record_end ""PERF.POWER"" || exit 1
e_time_power=`date +%s`
echo "`date`: Power Test completed."
diff_time=$(( $e_time_power - $s_time_power ))
echo "Elapsed time for Power Test : $diff_time seconds"

# Stop collecting system statistics.
read SARPID < ${OUTPUT_DIR}/sar.pid
kill ${SARPID}
read PIDSTATPID < ${OUTPUT_DIR}/pidstat.pid
kill ${PIDSTATPID}
read DBSTATPID < ${OUTPUT_DIR}/dbstat.pid
kill ${DBSTATPID}

dbt3-pgsql-stop-db || exit 1

if [ -f /proc/profile ]; then
	profname="Power_Test"
	getprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	profname="Power_Test"
	getoprof
fi

if [ $USE_LINUXPERF -eq 1 ]; then
	echo "Generating Linux perf reports for power test..."
	i=1
	while [ $i -le 22 ]; do
		PERFDIR=$OUTPUT_DIR/perf/$i
		PERFPREFIX=q$i
		perf report -i $PERFDIR/$PERFPREFIX-perf.data -n \
				> $PERFDIR/$PERFPREFIX-perf-report.txt &
		perf annotate -l -P -i $PERFDIR/$PERFPREFIX-perf.data \
				> $PERFDIR/$PERFPREFIX-perf-annotate.txt &
		perf script -L -i $PERFDIR/$PERFPREFIX-perf.data \
				> $PERFDIR/$PERFPREFIX-perf-trace.txt &
		i=$(( $i + 1 ))
	done > $OUTPUT_DIR/perf/report-output.txt 2>&1
	wait
fi

if [ $EXPLAIN -eq 1 ]; then
	# Generate plan disaster report only if EXPLAIN ANALYZE is used.
	DISASTERCSV=$OUTPUT_DIR/disaster.csv
	i=1
	while [ $i -le 22 ]; do
		dbt3-pgsql-plan-disaster $RESULTSDIR/$i.txt >> $DISASTERCSV
		i=$(( $i + 1 ))
	done
	sort -n -t "," -k 2 -r -o $DISASTERCSV $DISASTERCSV
fi
