#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

DIR=`dirname $0`
. ${DIR}/pgsql_profile || exit 1

# dont start script as root!
id=`id | sed s/\(.*// | sed s/uid=//`

if [ "$id" = "0" ]; then
	echo "dont start script as root"
	exit 1
fi

if [ -z ${PGDATA} ]; then
    echo "PGDATA not defined."
    exit 1
fi

if [ -z ${DBNAME} ]; then
    echo "DBNAME not defined."
    exit 1
fi

XLOGPATH=""
OUTPUT_DIR="."
while getopts "l:o:p:x:" OPT; do
	case ${OPT} in
	l)
		PORT=${OPTARG}
		PORTOPT="-p ${PORT}"
		;;
	o)
		OUTPUT_DIR=${OPTARG}
		;;
	p)
		PARAMETERS=${OPTARG}
		PARAMOPT="-p ${PARAMETERS}"
		;;
	x)
		XLOGPATH=${OPTARG}
		;;
	esac
done

dbt3-pgsql-stop-db

# Create database
echo "Creating database..."
if [ -d ${PGDATA} ]; then
	echo "PGData directory '${PGDATA}' already exists, skipping initdb..."
else
	# initialize database cluster
	echo "initializing database cluster..."
	initdb -A trust -D ${PGDATA} --locale=C || exit 1

	# Use alternative XLOG directory.
	if [ ! "x${XLOGPATH}" = "x" ]; then
	    mkdir -p ${XLOGPATH}
	    rm -rf ${XLOGPATH}/pg_xlog
	    mv ${PGDATA}/pg_xlog ${XLOGPATH}/pg_xlog || exit 1;
	    ln -s ${XLOGPATH}/pg_xlog ${PGDATA}/pg_xlog || exit 1;
	fi
fi

dbt3-pgsql-start-db ${PARAMOPT} || exit 1

createdb ${PORTOPT} ${DBNAME} || exit 1
#createlang ${PORTOPT} plpgsql ${DBNAME}

exit 0
