#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

DIR=`dirname $0`
. ${DIR}/pgsql_profile || exit 1

DBNAME=$SID

if [ "x${DBNAME}" = "x" ]; then
    echo "DBNAME not defined."
    exit 1
fi

while getopts "d:l:" OPT; do
	case ${OPT} in
	l)
		PORT=${OPTARG}
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi
PSQL="psql ${PORTARG} -e -d ${DBNAME}"

# need to consider table dependencies.
${PSQL} -e -c "DROP TABLE IF EXISTS supplier;"
${PSQL} -e -c "DROP TABLE IF EXISTS part;"
${PSQL} -e -c "DROP TABLE IF EXISTS partsupp;"
${PSQL} -e -c "DROP TABLE IF EXISTS customer;"
${PSQL} -e -c "DROP TABLE IF EXISTS orders;"
${PSQL} -e -c "DROP TABLE IF EXISTS lineitem;"
${PSQL} -e -c "DROP TABLE IF EXISTS nation;"
${PSQL} -e -c "DROP TABLE IF EXISTS region;"
${PSQL} -e -c "DROP TABLE IF EXISTS time_statistics;"
