#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Open Source Development Labs, Inc.
#               2003-2006 Jenny Zhang
#               2004-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#
#
# 2004 July 16 : Reworked by Mark Wong
# 2004 September 28 : Turn this into a wrapper script because we don't know
#                     how long the test will execute so we collect stats
#                     until the test is done.  Because of the way things are
#                     run in the background and we wait for processs to
#                     complete, we only want to wait for the processes that
#                     are executing the queries.

DIR=`dirname $0`
. ${DIR}/../dbt3_profile || exit 1

SRCDIR=${DBT3_HOME}

USE_OPROFILE=0
USE_LINUXPERF=0

TEST_ARGS=
NO_REFRESH=0
NO_REFRESH_FLAG=

while getopts "ef:l:n:o:p:s:t:yYz" opt; do
	case $opt in
	e) TEST_ARGS="$TEST_ARGS -e"
		;;
	f) scale_factor=$OPTARG
		;;
	l) DBPORT=$OPTARG
		;;
	n) num_stream=$OPTARG
		;;
	o) OUTPUT_DIR=$OPTARG
	   mkdir -p $OUTPUT_DIR/results
		;;
	p)
		PARAMETERS="${THROUGHPUT_PARAMETERS} $OPTARG"
		PARAMETERS_ARG="-p \"${THROUGHPUT_PARAMETERS} $OPTARG\""
		;;
	s) SEED_FILE=$OPTARG
		;;
	t) TAG=$OPTARG
		;;
	y) USE_OPROFILE=1
		;;
	Y) USE_LINUXPERF=1
		;;
	z) NO_REFRESH_FLAG="-z"
		NO_REFRESH=1
		;;
	esac
done

SEED=`cat $SEED_FILE`
echo "Seed : $SEED" > $OUTPUT_DIR/readme.txt

RUNDIR=$OUTPUT_DIR/run
mkdir -p $RUNDIR

DBSCRIPTDIR=$SRCDIR/scripts/pgsql
parsequery_dir="$SRCDIR/dbdriver/utils"

DBSTATS="${DBSCRIPTDIR}/db_stats.sh"

# Clear the read profile counters.
if [ -f /proc/profile ]; then
	clearprof
fi

# Clear the oprofile counters.
if [ $USE_OPROFILE -eq 1 ]; then
	clearoprof
fi

if [ ${USE_LINUXPERF} -eq 1 ]; then
	perf_start ${OUTPUT_DIR}/perf &
fi

$DBSCRIPTDIR/dbt3-pgsql-stop-db || exit 1
$DBSCRIPTDIR/dbt3-pgsql-start-db -o ${OUTPUT_DIR} ${PARAMETERS_ARG} || exit 1

s_time=`date +%s`
record_start "PERF${TAG}.THRUPUT" || exit 1

# Start collecting system statistics. 
$SRCDIR/scripts/dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 || exit 1

# Start collecting database statistics.
${DBSTATS} ${OUTPUT_DIR} ${DBPORT} &

# Start the streams.
${DBSCRIPTDIR}/throughput_stream_wrapper.sh -l ${DBPORT} -f ${scale_factor} \
		-t ${TAG} -n ${num_stream} ${TEST_ARGS} -o ${OUTPUT_DIR} \
		-s ${SEED_FILE} ${NO_REFRESH_FLAG} || exit 1

# Stop collecting system statistics.
read SARPID < ${OUTPUT_DIR}/sar.pid
kill ${SARPID}
read PIDSTATPID < ${OUTPUT_DIR}/pidstat.pid
kill ${PIDSTATPID}
read DBSTATSPID < ${OUTPUT_DIR}/db_stats.pid
kill ${DBSTATSPID}

record_end "PERF${TAG}.THRUPUT" || exit 1
e_time=`date +%s`
diff_time=$(( $e_time - $s_time ))
echo "Stream ${TAG} : Elapsed time for Throughput Test : $diff_time seconds"

# Stop the database after the test.
$DBSCRIPTDIR/dbt3-pgsql-stop-db || exit 1

if [ -f /proc/profile ]; then
	profname="Throughput_Test_$TAG"
	getprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	profname="Throughput_Test_$TAG"
	getoprof
fi

if [ ${USE_LINUXPERF} -eq 1 ]; then
	perf_collect ${OUTPUT_DIR}/perf
fi
