#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

DIR=`dirname $0`
. ${DIR}/pgsql_profile || exit 1

load_table()
{
	table=${1}
	file=${table}.tbl

	${PSQL} << __EOF__
COPY ${table} FROM '${DBDATA}/${file}' USING DELIMITERS '|';
__EOF__
}

supplier()
{
	load_table supplier

	${PSQL} -c "
ALTER TABLE supplier
ADD CONSTRAINT pk_supplier PRIMARY KEY (s_suppkey) ${TS_PK_SUPPLIER};" &
	${PSQL} -c "
CREATE INDEX
ON supplier (s_suppkey)
WHERE s_comment LIKE '%Customer%Complaints%';" &
	${PSQL} -c "
CREATE INDEX
ON supplier (s_nationkey, s_suppkey);" &

	wait

	${PSQL} -c "ANALZYE supplier;"
}

part()
{
	load_table part

	${PSQL} -c "
ALTER TABLE part
ADD CONSTRAINT pk_part PRIMARY KEY (p_partkey) ${TS_PK_PART};" &
	${PSQL} -c "
CREATE INDEX
ON part(p_type, p_partkey);" &
	${PSQL} -c "
CREATE INDEX
ON part(p_container,p_brand,p_partkey);" &
	${PSQL} -c "
CREATE INDEX
ON part(p_size);" &
	${PSQL} -c "
CREATE INDEX
ON part(p_name);" &

	wait

	${PSQL} -c "ANALZYE part;"
}

partsupp()
{
	load_table partsupp

	${PSQL} -c "
ALTER TABLE partsupp
ADD CONSTRAINT pk_partsupp
PRIMARY KEY (ps_partkey, ps_suppkey) ${TS_PK_PARTSUPP};" &
	${PSQL} -c "
CREATE INDEX i_ps_suppkey
ON partsupp (ps_suppkey) ${TS_I_PS_SUPPKEY};" &

	wait

	${PSQL} -c "ANALZYE partsupp;"
}

customer()
{
	load_table customer

	${PSQL} -c "
ALTER TABLE customer
ADD CONSTRAINT pk_customer PRIMARY KEY (c_custkey) ${TS_PK_CUSTOMER};" &
	${PSQL} -c "
CREATE INDEX
ON customer (c_nationkey, c_custkey);" &
	${PSQL} -c "
CREATE INDEX
ON customer (substr(c_phone::text, 1, 2))
WHERE c_acctbal > 0.00;" &
	${PSQL} -c "
CREATE INDEX
ON customer (substr(c_phone::text, 1, 2), c_acctbal);" &
	${PSQL} -c "
CREATE INDEX
ON customer (c_mktsegment, c_custkey);" &

	wait

	${PSQL} -c "ANALZYE customer;"
}

orders()
{
	load_table orders

	${PSQL} -c "
ALTER TABLE orders
ADD CONSTRAINT pk_orders PRIMARY KEY (o_orderkey) ${TS_PK_ORDERS};" &
	${PSQL} -c "
CREATE INDEX
ON orders (o_orderdate, o_orderkey);" &
	${PSQL} -c "
CREATE INDEX
ON orders (o_orderkey, o_orderdate);" &

	wait

	${PSQL} -c "ANALZYE orders;"
}

lineitem()
{
	load_table lineitem

	${PSQL} -c "
ALTER TABLE lineitem
ADD CONSTRAINT pk_lineitem PRIMARY KEY (l_orderkey, l_linenumber) ${TS_PK_LINEITEM};" &
	${PSQL} -c "
CREATE INDEX
ON lineitem (l_partkey, l_quantity, l_shipmode);" &
	${PSQL} -c "
CREATE INDEX
ON lineitem (l_orderkey);" &
	${PSQL} -c "
CREATE INDEX
ON lineitem (l_orderkey)
WHERE l_returnflag = 'R';" &
	${PSQL} -c "
CREATE INDEX
ON lineitem (l_orderkey)
WHERE l_commitdate < l_receiptdate;" &
	${PSQL} -c "
CREATE INDEX
ON lineitem (l_orderkey)
WHERE l_commitdate < l_receiptdate
  AND l_shipdate < l_commitdate;" &
	${PSQL} -c "
CREATE INDEX
ON lineitem (l_shipdate, l_suppkey);" &
	${PSQL} -c "
CREATE INDEX
ON lineitem (l_orderkey, l_linenumber, l_shipdate);" &

	wait

	${PSQL} -c "ANALZYE lineitem;"
}

nation()
{
	load_table nation

	${PSQL} -c "
ALTER TABLE nation
ADD CONSTRAINT pk_nation PRIMARY KEY (n_nationkey) ${TS_PK_NATION};" &

	wait

	${PSQL} -c "ANALZYE nation;"
}

region()
{
	load_table region

	${PSQL} -c "
ALTER TABLE region
ADD CONSTRAINT pk_region PRIMARY KEY (r_regionkey) ${TS_PK_REGION};" &

	wait

	${PSQL} -c "ANALZYE region;"
}

if [ -z ${DBNAME} ]; then
    echo "DBNAME not defined."
    exit 1
fi

USE_TABLESPACES=0
while getopts "bd:l:t" OPT; do
	case ${OPT} in
	d)
		DBDATA=${OPTARG}
		;;
	l)
		PORT=${OPTARG}
		;;
	t)
		USE_TABLESPACES=1
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi

PSQL="psql -v ON_ERROR_STOP=1 -X -p ${DBPORT} -d ${SID}"

supplier &
part &
partsupp &
customer &
orders &
lineitem &
nation &
region &

wait
