#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

create_table() {
	SQL=${1}

	${PSQL} << __EOF__
${SQL};
__EOF__
	return $?
}

NUM_OR_FD="NUMERIC"
USE_TABLESPACES=0
while getopts "t" OPT; do
	case ${OPT} in
	t)
		USE_TABLESPACES=1
		;;
	esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X -A -t"

# if the FIXEDDECIMAL extension exists, use it instead of NUMERIC (or REAL).
RC=`$PSQL -c "SELECT 1 FROM pg_extension WHERE extname = 'fixeddecimal';"`
if [ "x$RC" = "x1" ]; then
	NUM_OR_FD="FIXEDDECIMAL"
fi

if [ ${USE_TABLESPACES} -eq 1 ]; then
	TS_SUPPLIER_DIR="${TSDIR}/supplier/ts"
	TS_PART_DIR="${TSDIR}/part/ts"
	TS_PARTSUPP_DIR="${TSDIR}/partsupp/ts"
	TS_CUSTOMER_DIR="${TSDIR}/customer/ts"
	TS_ORDERS_DIR="${TSDIR}/orders/ts"
	TS_LINEITEM_DIR="${TSDIR}/lineitem/ts"
	TS_NATION_DIR="${TSDIR}/nation/ts"
	TS_REGION_DIR="${TSDIR}/region/ts"

	mkdir -p ${TS_SUPPLIER_DIR}
	mkdir -p ${TS_PART_DIR}
	mkdir -p ${TS_PARTSUPP_DIR}
	mkdir -p ${TS_CUSTOMER_DIR}
	mkdir -p ${TS_ORDERS_DIR}
	mkdir -p ${TS_LINEITEM_DIR}
	mkdir -p ${TS_NATION_DIR}
	mkdir -p ${TS_REGION_DIR}

	SUPPLIER_TABLESPACE="TABLESPACE dbt3_supplier"
	PART_TABLESPACE="TABLESPACE dbt3_part"
	PARTSUPP_TABLESPACE="TABLESPACE dbt3_partsupp"
	CUSTOMER_TABLESPACE="TABLESPACE dbt3_customer"
	ORDERS_TABLESPACE="TABLESPACE dbt3_orders"
	LINEITEM_TABLESPACE="TABLESPACE dbt3_lineitem"
	NATION_TABLESPACE="TABLESPACE dbt3_nation"
	REGION_TABLESPACE="TABLESPACE dbt3_region"

	${PSQL} -c "CREATE ${SUPPLIER_TABLESPACE} LOCATION '${TS_SUPPLIER_DIR}';"
	${PSQL} -c "CREATE ${PART_TABLESPACE} LOCATION '${TS_PART_DIR}';"
	${PSQL} -c "CREATE ${PARTSUPP_TABLESPACE} LOCATION '${TS_PARTSUPP_DIR}';"
	${PSQL} -c "CREATE ${CUSTOMER_TABLESPACE} LOCATION '${TS_CUSTOMER_DIR}';"
	${PSQL} -c "CREATE ${ORDERS_TABLESPACE} LOCATION '${TS_ORDERS_DIR}';"
	${PSQL} -c "CREATE ${LINEITEM_TABLESPACE} LOCATION '${TS_LINEITEM_DIR}';"
	${PSQL} -c "CREATE ${NATION_TABLESPACE} LOCATION '${TS_NATION_DIR}';"
	${PSQL} -c "CREATE ${REGION_TABLESPACE} LOCATION '${TS_REGION_DIR}';"
fi

create_table "
CREATE TABLE supplier (
	s_suppkey  INTEGER,
	s_name CHAR(25),
	s_address VARCHAR(40),
	s_nationkey INTEGER,
	s_phone CHAR(15),
	s_acctbal $NUM_OR_FD,
	s_comment VARCHAR(101))
	${SUPPLIER_TABLESPACE};" || exit 1

create_table "
CREATE TABLE part (
	p_partkey INTEGER,
	p_name VARCHAR(55),
	p_mfgr CHAR(25),
	p_brand CHAR(10),
	p_type VARCHAR(25),
	p_size INTEGER,
	p_container CHAR(10),
	p_retailprice $NUM_OR_FD,
	p_comment VARCHAR(23))
	${PART_TABLESPACE};" || exit 1

create_table "
CREATE TABLE partsupp (
	ps_partkey INTEGER,
	ps_suppkey INTEGER,
	ps_availqty INTEGER,
	ps_supplycost $NUM_OR_FD,
	ps_comment VARCHAR(199))
	${PARTSUPP_TABLESPACE};" || exit 1

create_table "
CREATE TABLE customer (
	c_custkey INTEGER,
	c_name VARCHAR(25),
	c_address VARCHAR(40),
	c_nationkey INTEGER,
	c_phone CHAR(15),
	c_acctbal $NUM_OR_FD,
	c_mktsegment CHAR(10),
	c_comment VARCHAR(117))
	${CUSTOMER_TABLESPACE};" || exit 1

create_table "
CREATE TABLE orders (
	o_orderkey INTEGER,
	o_custkey INTEGER,
	o_orderstatus CHAR(1),
	o_totalprice $NUM_OR_FD,
	o_orderdate DATE,
	o_orderpriority CHAR(15),
	o_clerk CHAR(15),
	o_shippriority INTEGER,
	o_comment VARCHAR(79))
	${ORDERS_TABLESPACE};" || exit 1

create_table "
CREATE TABLE lineitem (
	l_orderkey INTEGER,
	l_partkey INTEGER,
	l_suppkey INTEGER,
	l_linenumber INTEGER,
	l_quantity $NUM_OR_FD,
	l_extendedprice $NUM_OR_FD,
	l_discount $NUM_OR_FD,
	l_tax $NUM_OR_FD,
	l_returnflag CHAR(1),
	l_linestatus CHAR(1),
	l_shipdate DATE,
	l_commitdate DATE,
	l_receiptdate DATE,
	l_shipinstruct CHAR(25),
	l_shipmode CHAR(10),
	l_comment VARCHAR(44))
	${LINEITEM_TABLESPACE};" || exit 1

create_table "
CREATE TABLE nation (
	n_nationkey INTEGER,
	n_name CHAR(25),
	n_regionkey INTEGER,
	n_comment VARCHAR(152))
	${NATION_TABLESPACE};" || exit 1

create_table "
CREATE TABLE region (
	r_regionkey INTEGER,
	r_name CHAR(25),
	r_comment VARCHAR(152))
	${REGION_TABLESPACE};" || exit 1

create_table "
CREATE TABLE time_statistics (
	task_name VARCHAR(40),
	s_time TIMESTAMP,
	e_time TIMESTAMP);" || exit 1

${PSQL} << __EOF__
CREATE SEQUENCE dataset
MINVALUE 1
START WITH 1;
SELECT nextval('dataset');
__EOF__
