#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2015 Mark Wong
#               2015      2ndQuadrant, Ltd.
#

load_table()
{
	table=${1}
	file=${table}.tbl

	if [ $CHUNKS -eq 1 ] || [ "$table" = "nation" ] || \
			[ "$table" = "region" ]; then
		$PSQL << __EOF__
COPY $table FROM '$DSS_PATH/$file' USING DELIMITERS '|';
__EOF__
	else
		i=1
		while [ $i -le $CHUNKS ]; do
			$PSQL << __EOF__ &
COPY $table FROM '$DSS_PATH/$file.$i' USING DELIMITERS '|';
__EOF__
			i=$(( $i + 1 ))
		done
		wait
	fi
}

supplier()
{
	load_table supplier

	$PSQL << __EOF__ &
CREATE UNIQUE INDEX pk_supplier
ON supplier (s_suppkey)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX supplier_s_suppkey_idx_like
ON supplier (s_suppkey)
WITH (fillfactor = 100)
WHERE s_comment LIKE '%Customer%Complaints%';
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX supplier_s_nationkey_s_suppkey_idx
ON supplier (s_nationkey, s_suppkey)
WITH (fillfactor = 100);
__EOF__

	wait

	${PSQL} -c "VACUUM ANALYZE supplier;"
}

part()
{
	load_table part

	$PSQL << __EOF__ &
CREATE INDEX part_p_type_p_partkey_idx
ON part(p_type, p_partkey)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX part_p_container_p_brand_p_partkey_idx
ON part(p_container, p_brand, p_partkey)
WITH (fillfactor = 100);
__EOF__
	if [ $PGVERSION -ge 90500 ]; then
		$PSQL << __EOF__ &
CREATE INDEX part_ios_test1
ON part
USING btree (p_size, p_partkey, p_brand, p_type)
WITH (fillfactor = 100);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX part_p_size_idx ON part USING BRIN (p_size);
__EOF__
else
		$PSQL << __EOF__ &
CREATE INDEX part_p_size_idx
ON part(p_size);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX part_p_name_idx
ON part(p_name);
__EOF__
	fi

	wait

	${PSQL} -c "VACUUM ANALYZE part;"
}

partsupp()
{
	load_table partsupp

	$PSQL << __EOF__ &
CREATE UNIQUE INDEX pk_partsupp
ON partsupp (ps_partkey, ps_suppkey)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX partsupp_ps_suppkey_idx
ON partsupp (ps_suppkey)
WITH (fillfactor = 100);
__EOF__

	wait

	${PSQL} -c "VACUUM ANALYZE partsupp;"
}

customer()
{
	load_table customer

	$PSQL << __EOF__ &
CREATE UNIQUE INDEX pk_customer
ON customer (c_custkey)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX customer_c_nationkey_c_custkey_idx
ON customer (c_nationkey, c_custkey)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX customer_ios_test1
ON customer (substring(c_phone from 1 for 2), c_acctbal, c_custkey)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX customer_c_mktsegment_c_custkey_idx
ON customer (c_mktsegment, c_custkey)
WITH (fillfactor = 100);
__EOF__

	wait

	${PSQL} -c "VACUUM ANALYZE customer;"
}

orders()
{
	load_table orders

	$PSQL << __EOF__ &
CREATE UNIQUE INDEX pk_orders
ON orders (o_orderkey)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX orders_o_orderkey_o_orderdate_idx
ON orders (o_orderkey, o_orderdate)
WITH (fillfactor = 100);
__EOF__
	if [ $PGVERSION -ge 90500 ]; then
		$PSQL << __EOF__ &
CREATE INDEX orders_o_custkey_idx
ON orders (o_custkey)
WITH (fillfactor = 100);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX orders_o_orderdate_idx
ON orders USING BRIN (o_orderdate);
__EOF__
	else
		$PSQL << __EOF__ &
CREATE INDEX orders_o_orderdate_o_orderkey_idx
ON orders (o_orderdate, o_orderkey);
__EOF__
	fi

	wait

	${PSQL} -c "VACUUM ANALYZE orders;"
}

lineitem()
{
	load_table lineitem

	$PSQL << __EOF__ &
CREATE UNIQUE INDEX pk_lineitem
ON lineitem (l_orderkey, l_linenumber)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX lineitem_l_partkey_l_quantity_l_shipmode_idx
ON lineitem (l_partkey, l_quantity, l_shipmode)
WITH (fillfactor = 100);
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX lineitem_l_orderkey_idx_l_returnflag
ON lineitem (l_orderkey)
WITH (fillfactor = 100)
WHERE l_returnflag = 'R';
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX lineitem_l_orderkey_idx_part1
ON lineitem (l_orderkey, l_suppkey)
WITH (fillfactor = 100)
WHERE l_commitdate < l_receiptdate;
__EOF__
	$PSQL << __EOF__ &
CREATE INDEX lineitem_l_orderkey_idx_part2
ON lineitem (l_orderkey)
WITH (fillfactor = 100)
WHERE l_commitdate < l_receiptdate
  AND l_shipdate < l_commitdate;
__EOF__
	if [ $PGVERSION -ge 90500 ]; then
		$PSQL << __EOF__ &
CREATE INDEX line_item_l_orderkey_l_suppkey_idx
ON lineitem (l_orderkey, l_suppkey)
WITH (fillfactor = 100);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX lineitem_l_partkey_l_suppkey_l_shipdate_l_quantity_idx
ON lineitem (l_partkey, l_suppkey, l_shipdate, l_quantity)
WITH (fillfactor = 100);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX lineitem_l_shipdate_idx ON lineitem USING BRIN (l_shipdate);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX lineitem_l_receiptdate_idx ON lineitem USING BRIN (l_receiptdate);
__EOF__
	else
		$PSQL << __EOF__ &
CREATE INDEX lineitem_l_orderkey_idx
ON lineitem (l_orderkey);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX lineitem_l_shipdate_l_suppkey__idx
ON lineitem (l_shipdate, l_suppkey);
__EOF__
		$PSQL << __EOF__ &
CREATE INDEX lineitem_l_orderkey_l_linenumber_l_shipdate_idx
ON lineitem (l_orderkey, l_linenumber, l_shipdate);
__EOF__
	fi

	wait

	${PSQL} -c "VACUUM ANALYZE lineitem;"
}

nation()
{
	load_table nation

	$PSQL << __EOF__ &
CREATE UNIQUE INDEX pk_nation ON nation (n_nationkey) WITH (fillfactor = 100);
__EOF__

	wait

	${PSQL} -c "VACUUM ANALYZE nation;"
}

region()
{
	load_table region

	$PSQL << __EOF__ &
CREATE UNIQUE INDEX pk_region ON region (r_regionkey) WITH (fillfactor = 100);
__EOF__

	wait

	${PSQL} -c "VACUUM ANALYZE region;"
}

CHUNKS=1
USE_TABLESPACES=0
while getopts "C:t" OPT; do
	case ${OPT} in
	C)
		CHUNKS=$OPTARG
		;;
	t)
		USE_TABLESPACES=1
		;;
	esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X"
PGVERSION=`$PSQL -t --no-align -c "SHOW server_version_num;"`

supplier &
part &
partsupp &
customer &
orders &
lineitem &
nation &
region &

wait
