#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Open Source Development Labs, Inc.
#               2003-2006 Jenny Zhang
#               2004-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

USE_OPROFILE=0
USE_LINUXPERF=0

TEST_ARGS=
NO_REFRESH=0
NO_REFRESH_FLAG=

while getopts "ef:n:o:p:s:yYz" opt; do
	case $opt in
	e) TEST_ARGS="$TEST_ARGS -e"
		;;
	f) scale_factor=$OPTARG
		;;
	n) num_stream=$OPTARG
		;;
	o) OUTPUT_DIR=$OPTARG
	   mkdir -p $OUTPUT_DIR/results
		;;
	p)
		PARAMETERS_ARG="-p \"$OPTARG\""
		;;
	s) SEED_FILE=$OPTARG
		;;
	y) USE_OPROFILE=1
		;;
	Y) USE_LINUXPERF=1
		LINUXPERF_FLAG="-Y"
		;;
	z) NO_REFRESH_FLAG="-z"
		NO_REFRESH=1
		;;
	\?) exit 1
		;;
	esac
done

read SEED < $SEED_FILE
echo "Seed : $SEED" > $OUTPUT_DIR/readme.txt

RUNDIR=$OUTPUT_DIR/run
mkdir -p $RUNDIR

# Clear the read profile counters.
if [ -f /proc/profile ]; then
	clearprof
fi

# Clear the oprofile counters.
if [ $USE_OPROFILE -eq 1 ]; then
	clearoprof
fi

if [ $USE_LINUXPERF -eq 1 ]; then
	PERFDIR=$OUTPUT_DIR/perf
	mkdir -p $PERFDIR
	PERFCOMMAND="perf record -a -g -s -F 100 -o $PERFDIR/perf.data"
fi

dbt3-pgsql-stop-db || exit 1
eval dbt3-pgsql-start-db -o $OUTPUT_DIR $PARAMETERS_ARG || exit 1

s_time=`date +%s`
psql -v ON_ERROR_STOP=1 -X -q << __EOF__ > /dev/null 2>&1
INSERT INTO time_statistics (task_name, s_time)
VALUES ('PERF.THRUPUT', CURRENT_TIMESTAMP);
__EOF__

# Start collecting system statistics. 
dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 || exit 1

# Start collecting database statistics.
dbt3-pgsql-dbstat ${OUTPUT_DIR} &

# Start the streams.
eval $PERFCOMMAND dbt3-pgsql-throughput-stream-wrapper -f $scale_factor \
		-n $num_stream $TEST_ARGS -o $OUTPUT_DIR -s $SEED_FILE \
		$NO_REFRESH_FLAG $LINUXPERF_FLAG || exit 1

# Stop collecting system statistics.
read SARPID < ${OUTPUT_DIR}/sar.pid
kill ${SARPID}
read PIDSTATPID < ${OUTPUT_DIR}/pidstat.pid
kill ${PIDSTATPID}
read DBSTATPID < ${OUTPUT_DIR}/dbstat.pid
kill ${DBSTATPID}

psql -v ON_ERROR_STOP=1 -X -q << __EOF__ > /dev/null 2>&1
UPDATE time_statistics
SET e_time = current_timestamp
WHERE task_name = 'PERF.THRUPUT';
__EOF__
e_time=`date +%s`
diff_time=$(( $e_time - $s_time ))
echo "Elapsed time for Throughput Test : $diff_time seconds"

# Stop the database after the test.
dbt3-pgsql-stop-db || exit 1

if [ -f /proc/profile ]; then
	profname="Throughput_Test"
	getprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	profname="Throughput_Test"
	getoprof
fi

if [ $USE_LINUXPERF -eq 1 ]; then
	echo "Generating Linux perf reports for throughput test..."
	perf report -i $PERFDIR/perf.data -n > $PERFDIR/perf-report.txt \
			2>> $OUTPUT_DIR/perf/report-output.txt &
	perf annotate -l -P -i $PERFDIR/perf.data > $PERFDIR/perf-annotate.txt \
			2>> $OUTPUT_DIR/perf/report-output.txt &
	perf script -L -i $PERFDIR/perf.data > $PERFDIR/perf-trace.txt \
			2>> $OUTPUT_DIR/perf/report-output.txt &

	i=1
	while [ $i -le $num_stream ]; do
		j=1
		while [ $j -le 22 ]; do
			PERFDIR=$OUTPUT_DIR/results/$i/perf/$j
			PERFPREFIX=q$j
			perf report -i $PERFDIR/$PERFPREFIX-perf.data -n \
					> $PERFDIR/$PERFPREFIX-perf-report.txt &
			perf annotate -l -P -i $PERFDIR/$PERFPREFIX-perf.data \
					> $PERFDIR/$PERFPREFIX-perf-annotate.txt &
			perf script -L -i $PERFDIR/$PERFPREFIX-perf.data \
					> $PERFDIR/$PERFPREFIX-perf-trace.txt &
			j=$(( $j + 1 ))
		done
		i=$(( $i + 1 ))
	done > $OUTPUT_DIR/perf/perf-output.txt 2>&1
	wait
fi
