#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2008 Rod Taylor
#               2015      Mark Wong
#               2015      2ndQuadrant, Ltd.

if [ -z ${PGDATA} ]; then
	echo "PGDATA not defined."
	exit 1
fi

pg_ctl -Z coordinator -w -D $COORDINATORDATA stop -m fast

i=1
for HOSTNAME in $HOSTNAMES; do
	j=1
	while [ $j -le $DNPN ]; do
		ssh $HOSTNAME "pg_ctl -Z datanode -w -D $DATANODEDATA$i.$j stop -m fast"
		j=$(( $j + 1 ))
	done
	i=$(( $i + 1 ))
done

i=1
for HOSTNAME in $HOSTNAMES; do
	ssh $HOSTNAME "gtm_ctl -Z gtm_proxy -D $GTMPROXYDATA$i stop -m fast"
	i=$(( $i + 1 ))
done

gtm_ctl -D $GTMDATA -Z gtm stop -m fast
