#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2008 Rod Taylor
#               2015      Mark Wong
#               2015      2ndQuadrant, Ltd.

if [ -z ${PGDATA} ]; then
	echo "PGDATA not defined."
	exit 1
fi

pgxc_ctl stop all
