#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002 Open Source Development Lab, Inc.
#               2002 Jenny Zhang 
#               2014 Mark Wong
#               2014 2ndQuadrant, Ltd.
#

export DSS_QUERY="/home/mark/src/dbt3/queries/pgsql"
export DSS_PATH="/tmp/dss_path"
export DSS_CONFIG="/home/mark/src/dbt3/src/dbgen"

export DBGEN="${DSS_CONFIG}/dbgen"
export QGEN="${DSS_CONFIG}/qgen"

clearprof()
{
	sudo /usr/sbin/readprofile -m /boot/System.map-`uname -r` -r
}

getprof()
{
	sudo /usr/sbin/readprofile -n -m /boot/System.map-`uname -r` -v | sort -grk3,4 > $OUTPUT_DIR/readprofile.txt
}

clearoprof()
{
	sudo opcontrol --vmlinux=/boot/vmlinux
	sleep 2
	sudo opcontrol --start-daemon
	sleep 2
	sudo opcontrol --start
	sleep 2
	# If opcontrol ever gets stuck here, sometimes it helps to remove
	# everything in this dir:
	# /var/lib/oprofile
	sudo opcontrol --reset
}

getoprof()
{
	mkdir -p $OUTPUT_DIR/oprofile/annotate
	sudo opcontrol --dump
	sudo opreport -l -o $OUTPUT_DIR/oprofile/oprofile.txt
	sudo opcontrol --stop
	sudo opcontrol --shutdown
	sudo opannotate --source --assembly > $OUTPUT_DIR/oprofile/assembly.txt 2>&1
	sudo opannotate --source --output-dir=$OUTPUT_DIR/oprofile/annotate
	sudo opreport -l -c -p /lib/modules/`uname -r` \
			-o ${OUTPUT_DIR}/oprofile/call-graph.txt > /dev/null 2>&1
}

perf_start()
{
	DIR=${1}

	mkdir -p ${DIR}
	sudo perf record -o ${DIR}/perf.data -a -g -s sleep 60
}

perf_collect()
{
	DIR=${1}

	echo "Generating perf report..."
	sudo perf report -i ${DIR}/perf.data -n > ${DIR}/perf-report.txt &

	echo "Generating perf annotated source..."
	sudo perf annotate -l -P -i ${DIR}/perf.data > ${DIR}/perf-annotate.txt &

	echo "Generating perf trace on..."
	sudo perf script -L -i ${DIR}/perf.data > ${DIR}/perf-trace.txt &
}
