#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002     Open Source Development Lab, Inc.
#               2002     Jenny Zhang
#               2014     Mark Wong
#               2014     2ndQuadrant, Ltd.
#

export DBT3_DIR=~/local/dbt3

export PGDATABASE=dbt3
export PGDATA=$DBT3_DIR/pgdata

# To set the pg_xlog directory, uncomment and modify appropriately.
#export PGXLOG_ARG="-X /mnt/pg_xlog"

export PGPORT=5432

export DEFAULT_LOAD_PARAMETERS=""
export DEFAULT_POWER_PARAMETERS=""
export DEFAULT_THROUGHPUT_PARAMETERS=""

# Directory with tablespace mount points, if using tablespaces.
export TSDIR=${DBT3_DIR}
