#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Open Source Development Labs, Inc.
#               2003-2006 Jenny Zhang
#               2005-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

make_sar_csv() {
	local FILE=$1

	local DIR=`dirname ${FILE}`

	${SADF} -P ALL ${FILE} > ${DIR}/sar-cpu.csv
	${SADF} ${FILE} -- -B > ${DIR}/sar-paging.csv
	${SADF} ${FILE} -- -d -p > ${DIR}/sar-blockdev.csv
	${SADF} ${FILE} -- -R > ${DIR}/sar-mem1.csv
	${SADF} ${FILE} -- -r > ${DIR}/sar-mem2.csv
	${SADF} ${FILE} -- -W > ${DIR}/sar-swap.csv
	$SADF $FILE -- -n DEV > $DIR/sar-net.csv
}

PLOT_OPTS=""
FLAG_POWER_TEST=0
FLAG_THROUGHPUT_TEST=0
while getopts "23i:n:o:s:z" OPT; do
	case ${OPT} in
	2)
		FLAG_POWER_TEST=1
		PLOT_OPTS="${PLOT_OPTS} -2"
		;;
	3)
		FLAG_THROUGHPUT_TEST=1
		PLOT_OPTS="${PLOT_OPTS} -3"
		;;
	i)
		INDIR=$OPTARG
		QTIME=$INDIR/q_time.csv
		;;
	n)
		STREAMS=${OPTARG}
		;;
	o)
		OUTFILE=${OPTARG}
		;;
	s)
		SCALE_FACTOR=${OPTARG}
		;;
	z)
		NO_REFRESH_FLAG="-z"
		PLOT_OPTS="${PLOT_OPTS} -z"
		;;
	\?)
		exit 1
		;;
	esac
done

# Try to make sure the outfile is created.
echo "" > ${OUTFILE}

which sadf > /dev/null 2>&1
if [ $? -eq 0 ]; then
	SADF="sadf -d -U"
	$SADF 1 1 > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		SADF="sadf -D"
		$SADF 1 1 > /dev/null 2>&1
		if [ $? -ne 0 ]; then
			echo "WARNING: Was not able to determine proper sadf flags"
			SADF="true"
		fi
	fi
else
	SADF=true
fi

for SARFILE in `find $INDIR -name sar_raw.out`; do
	make_sar_csv $SARFILE
done

if [ ${FLAG_POWER_TEST} -eq 1 ]; then
	POWER=`dbt3-power-score -i $QTIME -s $SCALE_FACTOR $NO_REFRESH_FLAG`
	echo "power = $POWER"  | tee -a $OUTFILE
fi

if [ ${FLAG_THROUGHPUT_TEST} -eq 1 ]; then
	THROUGHPUT=`dbt3-throughput-score -i $QTIME -s $SCALE_FACTOR -n $STREAMS`
	echo "throughput = $THROUGHPUT" | tee -a $OUTFILE
fi

if [ ${FLAG_POWER_TEST} -eq 1 ] && [ ${FLAG_THROUGHPUT_TEST} -eq 1 ]; then
	COMPOSITE=`echo "scale=2; sqrt(${POWER} * ${THROUGHPUT})" | bc -l`
	echo "composite = ${COMPOSITE}" | tee -a ${OUTFILE}
fi
