#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Jenny Zhang & Open Source Development Labs, Inc.
#               2003-2006 Open Source Development Labs, Inc.
#               2005-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

FLAG_POWER_TEST=0
FLAG_THROUGHPUT_TEST=0
while getopts "23i:n:o:s:z" OPT; do
	case ${OPT} in
	2)
		FLAG_POWER_TEST=1
		;;
	3)
		FLAG_THROUGHPUT_TEST=1
		;;
	i)
		INFILE=${OPTARG}
		;;
	n)
		STREAMS=${OPTARG}
		;;
	o)
		OUTFILE=${OPTARG}
		;;
	s)
		SCALE_FACTOR=${OPTARG}
		;;
	z)
		NO_REFRESH_FLAG="-z"
		;;
	esac
done

#
# Make sure the outfile is created.
#
cat /dev/null > ${OUTFILE}

if [ ${FLAG_POWER_TEST} -eq 1 ]; then
	POWER=`dbt3-power-score -i ${INFILE} -s ${SCALE_FACTOR} ${NO_REFRESH_FLAG}`
	echo "power = ${POWER}" | tee -a ${OUTFILE}
fi

if [ ${FLAG_THROUGHPUT_TEST} -eq 1 ]; then
	THROUGHPUT=`dbt3-throughput-score -i ${INFILE} -s ${SCALE_FACTOR}`
	echo "throughput = ${THROUGHPUT}" | tee -a ${OUTFILE}
fi

if [ ${FLAG_POWER_TEST} -eq 1 ] && [ ${FLAG_THROUGHPUT_TEST} -eq 1 ]; then
	COMPOSITE=`echo "scale=2; sqrt(${POWER} * ${THROUGHPUT})" | bc -l`
	echo "composite = ${COMPOSITE}" | tee -a ${OUTFILE}
fi
