#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2015      Mark Wong
#               2015      2ndQuadrant, Ltd.
#

if [ -z $DBNAME ]; then
	echo "DBNAME not defined."
	exit 1
fi

MCLIENT="mclient -d $DBNAME"

load_table()
{
	table=$1
	file=$table.tbl
	
	$MCLIENT -d $DBNAME << __EOF__
COPY INTO $table FROM '$DSS_PATH/$table.tbl' USING DELIMITERS '|', '\n' LOCKED;
__EOF__
}

# FIXME: Can't load more than two tables simultaneously, something locks up.
load_table supplier
load_table part
load_table partsupp
load_table customer
load_table orders
load_table lineitem
load_table nation
load_table region

$MCLIENT << __EOF__
ALTER TABLE supplier ADD CONSTRAINT suppkey PRIMARY KEY (s_suppkey);
ALTER TABLE part ADD CONSTRAINT partkey PRIMARY KEY (p_partkey);
ALTER TABLE partsupp
ADD CONSTRAINT partsuppkey
PRIMARY KEY (ps_partkey, ps_suppkey);
ALTER TABLE customer ADD CONSTRAINT custkey PRIMARY KEY (c_custkey);
ALTER TABLE orders ADD CONSTRAINT orderkey PRIMARY KEY (o_orderkey);
ALTER TABLE lineitem
ADD CONSTRAINT lineitemkey
PRIMARY KEY (l_orderkey,l_linenumber);
ALTER TABLE nation ADD CONSTRAINT nationkey PRIMARY KEY (n_nationkey);
ALTER TABLE region ADD CONSTRAINT regionkey PRIMARY KEY (r_regionkey);

ALTER TABLE supplier
ADD CONSTRAINT supplier_nationkey
FOREIGN KEY (s_nationkey)
REFERENCES nation (n_nationkey);

ALTER TABLE partsupp
ADD CONSTRAINT partsupp_partkey
FOREIGN KEY (ps_partkey)
REFERENCES part (p_partkey);

ALTER TABLE partsupp
ADD CONSTRAINT partsupp_suppkey
FOREIGN KEY (ps_suppkey)
REFERENCES supplier (s_suppkey);

ALTER TABLE customer
ADD CONSTRAINT customer_nationkey
FOREIGN KEY (c_nationkey)
REFERENCES nation (n_nationkey);

ALTER TABLE orders
ADD CONSTRAINT order_custkey
FOREIGN KEY (o_custkey)
REFERENCES customer (c_custkey);

ALTER TABLE lineitem
ADD CONSTRAINT lineitem_orderkey
FOREIGN KEY (l_orderkey)
REFERENCES orders (o_orderkey);

ALTER TABLE lineitem
ADD CONSTRAINT lineitem_partkey
FOREIGN KEY (l_partkey)
REFERENCES part (p_partkey);

ALTER TABLE lineitem
ADD CONSTRAINT lineitem_suppkey
FOREIGN KEY (l_suppkey)
REFERENCES supplier (s_suppkey);

ALTER TABLE lineitem
ADD CONSTRAINT lineitem_partsuppkey
FOREIGN KEY (l_partkey,l_suppkey)
REFERENCES partsupp (ps_partkey,ps_suppkey);

ALTER TABLE nation
ADD CONSTRAINT nation_regionkey
FOREIGN KEY (n_regionkey)
REFERENCES region (r_regionkey);
__EOF__
wait
