#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

if [ -z $DBNAME ]; then
	echo "DBNAME not defined."
	exit 1
fi

mclient -d $DBNAME << __EOF__
DROP TABLE supplier CASCADE;
DROP TABLE part CASCADE;
DROP TABLE partsupp CASCADE;
DROP TABLE customer CASCADE;
DROP TABLE orders CASCADE;
DROP TABLE lineitem CASCADE;
DROP TABLE nation CASCADE;
DROP TABLE region CASCADE;
DROP TABLE time_statistics;
__EOF__
