#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2015      Mark Wong
#               2015      2ndQuadrant, Ltd.

if [ -z $DBNAME ]; then
	echo "DBNAME not defined."
	exit 1
fi

if [ $# -ne 1 ]; then
        echo "Usage: `$0` <scale factor>"
        exit 1
fi

SCALE_FACTOR=$1

MCLIENT="mclient -d $DBNAME"
DATASET=`$MCLIENT -s "SELECT next_value_for('sys', 'dataset');" -f csv`
if [ $? -ne 0 ]; then
	echo "ERROR: cannot get dataset number"
	exit 1
fi
dbgen -s $SCALE_FACTOR -U $DATASET -S $DATASET || exit 1

echo "`date`: Stream $DATASET : Starting Refresh Stream 1..."
s_time=`date +%s`

$MCLIENT << __EOF__
START TRANSACTION;

COPY INTO lineitem
FROM '$DSS_PATH/lineitem.tbl.u$DATASET'
USING DELIMITERS '|', '\n';

COPY INTO orders
FROM '$DSS_PATH/orders.tbl.u$DATASET'
USING DELIMITERS '|', '\n';

COMMIT;
__EOF__

e_time=`date +%s`
echo "`date`: Stream $DATASET : Refresh Stream 1 completed."
diff_time=$(( $e_time - $s_time ))
echo "Stream $DATASET : Elapsed time for Refresh Stream 1 : $diff_time seconds"

if [ $DATASET -gt 0 ]; then
	exit $DATASET
fi
exit -1
