#!/bin/sh
#
# This file is released under the terms of the Artistic License.  Please see
# the file LICENSE, included in this package, for details.
#
# Copyright (C) 2015      Mark Wong
#               2015      2ndQuadrant, Ltd.

if [ -z $DBNAME ]; then
	echo "DBNAME not defined."
	exit 1
fi

# Here script doesn't work, and csv output doesn't include header.
mclient -f csv -d $DBNAME \
		-s "SELECT 'task_name', 's_time', 'e_time', 'diff_time', 'seconds';"
mclient -f csv -d $DBNAME \
		-s "SELECT task_name, s_time, e_time, NULL, e_time - s_time FROM time_statistics;"
